### ISSUE TITLE
 [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by holder-fo** [GoogleCloudPlatform/plspm-python#6] opened 2020-07-28 11:46 UTC
Hi Jez.
I run the data and code same as uploaded in issue #5 and bump into this error with the latest 0.5.5. I have no idea how to deal with it, hope you can help me.

**Comment by jezhumble** [comment] 2020-07-31 02:24
I expect it's an issue with the multi-core bootstrapping support in 0.5.5. If you downgrade to 0.5.4 it should work.

Please can you supply me with your latest code so I can debug, since due to the fix I put in 0.5.4 your code does not work for me (it has LVs with the same names as MVs)

**Comment by holder-fo** [comment] 2020-07-31 02:50
Yes, it's an issue with multi-core bootstrapping. Sadly i have no knowledge to deal with it and have to bother you again.
Thanks for your warm-hearted reply again! Code and data follow here:
[sem-try (2).txt](https://github.com/GoogleCloudPlatform/plspm-python/files/5004794/sem-try.2.txt)
[mod_data.txt](https://github.com/GoogleCloudPlatform/plspm-python/files/5004795/mod_data.txt)

**Comment by jezhumble** [comment] 2020-08-02 18:27
Please can you let me know what operating system you are running this on (for example Microsoft Windows 10) and also your system details (for example Lenovo P53 with 1.2 GHz Quad-Core Intel Core i7 and 8Gb RAM)?

Also, what version of Python are you running?

Your code runs fine on my Apple MacBook, I am guessing it is some OS/system specific issue that I will need to try and reproduce.

**Comment by holder-fo** [comment] 2020-08-03 02:04
I am using Python 3.7.7 in a Desktop with Intel(R)_Core(TM)_i5-9600K_CPU_@_3.70GHz and  8Gb RAM running Microsoft Windows 10 (1909/18363.900).
Please tell me if any more info you need.
Thanks for your patience again!

**Comment by jezhumble** [comment] 2020-08-03 03:50
Thanks. I don't have a Windows machine to debug on so I will need to get a virtual machine set up. In the meantime, another workaround to try is to set `processes=1` when initializing Plspm, for example: `    calc = Plspm(data, config, Scheme.PATH, 300, 0.0000001, bootstrap=True, bootstrap_iterations=300, processes=1)`

**Comment by soumyaray** [comment] 2020-08-03 04:45
@jezhumble i'm following this and other issues to see if there's any opportunity to help.  I'm wondering if a CI solution (perhaps something within Google) could help setup virtual machines for testing?  We're using Travis CI for seminr but only examining linux and mac.  Will have to inquire with my own team why we are not examining windows.

**Comment by jezhumble** [comment] 2020-08-06 17:04
So I didn't get the "broken pipe" error but I did get another error when running multicore on Windows 10 which I have fixed - see 0.5.6 which I just released. Bootstrapping now works on my Windows test environment - please take a look and see if that fixes it for you. Sorry it took a while, and thanks for reporting.

Soumya - thanks for stepping in. I agree, adding CI a good idea, I just haven't gotten round to it, but this is definitely a good push to prioritize.

**Comment by holder-fo** [comment] 2020-08-08 12:09
Hi, jez.
I upgraded and tested it, it works fine when processes=1 or 2, but not for processes>2.
So please can you check this for me?

**Comment by jezhumble** [comment] 2020-08-08 16:16
Thanks for the update. I just ran your code on my VM with 4 processors and it seems to be OK, but I expect this problem is very system dependent so I am going to get a more robust setup and try with more processors. In the meantime, please can you copy and paste your complete output from running your code into a comment?

![windows10](https://user-images.githubusercontent.com/155194/89715047-c644c800-d957-11ea-86e9-498284c0868e.png)

**Comment by holder-fo** [comment] 2020-08-09 08:42
I run it with 2 processors in Pycharm and it output same as yours.
![20200809164121](https://user-images.githubusercontent.com/40030047/89728339-34c07d80-da5f-11ea-9157-09e94f6149f3.png)

**Comment by jezhumble** [comment] 2020-08-09 17:26
My apologies - I was looking for the output from when it fails with 4 processors.

**Comment by holder-fo** [comment] 2020-08-11 12:09
Sorry i didn't check notifications in time. When i run it with 4 processors, it never output due to endless calculating and i had to end it manually.

**Comment by holder-fo** [comment] 2020-08-12 00:54
My mistake!  I rerun it with 4 processors and output normally but the cost time is way too long so i had to end it manually before.

**Comment by jezhumble** [comment] 2020-08-13 04:33
Thanks for the update and for your patience working through this. Yes, unfortunately bootstrapping is especially slow. I will look at further performance enhancements. In the meantime, if you need more speed, R is the way to go. Closing this for now.

**Closed as completed by jezhumble** 2020-08-13 04:33 UTC
Labels: bug

**Comment by holder-fo** [comment] 2020-08-14 01:13
Thanks for your dedicated work! I am ok with the speed of bootstrapping now since i need it much.
Actually，what i wonder is why i run it with 4 processors is slower than 2 processors because i have no clue. Anyway, thanks  for the multiprocessing it speed up than 1 processor.
